import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";

 
export const metadata: Metadata = {
  title: "MaxClean - Premium Doorstep Carwash Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={``}
      >
        {children}
      </body>
      
    </html>
  );
}
